apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-python-app.fullname" . }}
  labels:
    {{- include "devops-python-app.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
