apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "devops-python-app.labels" . | nindent 4 }}
type: Opaque
data:
  pg_creds: {{ .Values.secret.pg_creds | b64enc | quote }}
