apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devops-python-app.fullname" . }}
  labels:
    {{- include "devops-python-app.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.service.name }}
  podManagementPolicy: {{ .Values.statefulSet.podManagementPolicy }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "devops-python-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "devops-python-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "devops-python-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: download-cats
          image: busybox
          command:
            - wget
            - "-O"
            - "/downloads/cats.htm"
            - {{ .Values.cats.url }}
          volumeMounts:
            - name: downloads
              mountPath: "/downloads"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PG_CREDS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: pg_creds
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.volumes.config }}
              readOnly: true
            - name: visits
              mountPath: {{ .Values.volumes.visits }}
            - name: downloads
              mountPath: {{ .Values.volumes.downloads }}
      volumes:
        - name: config
          configMap:
            name: {{ include "devops-python-app.fullname" . }}
        - name: downloads
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: visits
      spec:
        {{- toYaml .Values.statefulSet.volumeClaimTemplates.spec | nindent 8 }}
