apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-python-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-python-app
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: devops-python-app
    spec:
      containers:
      - name: devops-python-app
        image: dantara/devops-python-app:latest
        ports:
        - containerPort: 5000
