apiVersion: v1
kind: Service
metadata:
  name: devops-python-app-service
spec:
  selector:
    app: devops-python-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000 # host port
      targetPort: 5000  # container port
